; Settings are reloaded whenever the Pip-Boy opens. No need to restart the game.

[General]

; Enable the fullscreen power-armor Pip-Boy interface when outside PA
bForcePowerArmorPipboy=1

; Play the Power Armor Pip-Boy open/close sounds
bPowerArmorAudio=1

; Keeps the Pip-Boy light on when Pip-Boy is open (like it does with Power Armor)
bKeepPipboyLightOn=1

; Bonus feature: Rain overlay on the screen even when outside Power Armor
bRainOverlayOutsidePowerArmor=0

; Power armor Pip-Boy has a fixed orange color. This will make it inherit the Pip-Boy text color set in your Fallout4.INI.
bUsePipboyEffectColor=0

; Enables debug logging
bEnableDebugLogging=1
